### ISSUE TITLE
mnist_demo.py提示“ImportError: No module named Image”

### ISSUE THREAD

**Issue by edongyu** [wlmnzf/tensorflow-train#3]
已经用pip install image，但是运行代码mnist_demo.py依然提示“ImportError: No module named Image”错误 ,  查看mnist_demo.py代码里直接写的import Image 就会报错， 改成from PIL import Image 就不报错误了， 不知道大家在用的时候有没有遇到这个问题， 如何才能不用from PIL 而不报错呢？

**Comment by zli2014** [comment]
这个是tensorflow版本的问题, 你可以在statck overflow中找到 查找的关键字为 Tensorflow ImportError: No module named Image

**Comment by suifeng9** [comment]
请问mnist_demo运行结束，有什么结果输出么？接下来怎么运行程序呢
他readme里没说怎么使用自己的数据集，谢谢

**Comment by wlmnzf** [comment]
http://write.blog.csdn.net/postedit/51040158           文章在这里
